/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pokerGameProxySol from "./PokerGameProxy.sol";
export type { pokerGameProxySol };
export type { PokerGameProxyFactory } from "./PokerGameProxyFactory";
