/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as pokerGameProxySol from "./PokerGameProxy.sol";
export { PokerGameProxyFactory__factory } from "./PokerGameProxyFactory__factory";
