/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProxy__factory } from "./IProxy__factory";
export { PokerGameProxy__factory } from "./PokerGameProxy__factory";
