/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as core from "./core";
export type { core };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as proxy from "./proxy";
export type { proxy };
export * as factories from "./factories";
export type { PokerGameSingleton } from "./core/PokerGameSingleton";
export { PokerGameSingleton__factory } from "./factories/core/PokerGameSingleton__factory";
export type { IProxyCreationCallback } from "./interfaces/IProxyCreationCallback";
export { IProxyCreationCallback__factory } from "./factories/interfaces/IProxyCreationCallback__factory";
export type { IProxy } from "./proxy/PokerGameProxy.sol/IProxy";
export { IProxy__factory } from "./factories/proxy/PokerGameProxy.sol/IProxy__factory";
export type { PokerGameProxy } from "./proxy/PokerGameProxy.sol/PokerGameProxy";
export { PokerGameProxy__factory } from "./factories/proxy/PokerGameProxy.sol/PokerGameProxy__factory";
export type { PokerGameProxyFactory } from "./proxy/PokerGameProxyFactory";
export { PokerGameProxyFactory__factory } from "./factories/proxy/PokerGameProxyFactory__factory";
